language: python
python:
  - "2.6"
  - "2.7"
addons:
  apt:
    packages:
    - time
    - ansible
install:
  - "pip install --upgrade setuptools pip"
  - "pip install -e .[openstack]"
script: pytest -v

