---
- name: Ensure /data directory exists
  hosts: usz_data_export:usz_data_import
  tasks:
    - action: file path=/data state=directory owner={{ ansible_ssh_user }}
    - action: file path=/apps state=directory owner={{ ansible_ssh_user }}
    - action: file path=/data-scratch state=directory owner={{ ansible_ssh_user }}
  sudo: yes

- name: Ensure scripts and stdout directories exists
  hosts: usz_data_export
  tasks:
    - action: file path=~{{ ansible_ssh_user }}/scripts state=directory owner={{ ansible_ssh_user }}
    - action: file path=~{{ ansible_ssh_user }}/stdout state=directory owner={{ ansible_ssh_user }}
    - action: file path=/apps state=directory owner={{ ansible_ssh_user }}
  sudo: yes

- name: Data export
  hosts: usz_data_export
  tasks: 
    - include: common/tasks/nfs.yml
    - action: nfsexport path=/data dest=/etc/exports clients=${groups.usz_data_import} options=rw,no_root_squash,sync
    - action: nfsexport path=/data-scratch dest=/etc/exports clients=${groups.usz_data_import} options=rw,no_root_squash,sync
    - action: nfsexport path=/apps dest=/etc/exports clients=${groups.usz_data_import} options=rw,no_root_squash,sync

- name: Data Import
  hosts: usz_data_import
  tasks: 
    - include: common/tasks/nfs-clients.yml nfsserver=${groups.usz_data_export[0]} nfspath=/data nfsmount=/data remount='true'
    - include: common/tasks/nfs-clients.yml nfsserver=${groups.usz_data_export[0]} nfspath=/data-scratch nfsmount=/data-scratch remount='true'
    - include: common/tasks/nfs-clients.yml nfsserver=${groups.usz_data_export[0]} nfspath=/apps nfsmount=/apps remount='true'
    - include: gridengine/tasks/clients.yml
