---
- name: Prepare node for Matlab installation
  hosts: matlab
  vars:
    openstack_credential_file: '/home/sergio/.gc3cloud/hobbes.academic-cloud.openstack.sh'
    vm_id: 'f811901a-34e0-44b4-a432-5473173d0ca0'
    volume_id: '9ad3ebda-653b-41d6-8535-63e8c1b457b8'
    volume_device: '/dev/vdb'
    download_dir: '/var/tmp'
    iso_mount_point: '/mnt/matlab/'
    volume_mount_point: '/mnt/iso/'
    matlab_version: 'R2014a'
    matlab_FIK: '58805-27286-31944-04174-45421-41476-39491-11725-01367-42497-54340-58977-14089-47399-05567-14623-43721'
    matlab_license_server: 'idlicense1.uzh.ch 0060975bfa00 1712'
    matlab_install_dir: '/usr/local'
    http_repo: 'ftp://campussoftware.uzh.ch/Matlab/.previous/Linux/{{ matlab_version }}_UNIX.iso'
    volume_device: '/dev/vdb'
    download_iso: false
  tasks:
    - name: Install dependencies (Ubuntu/Debian)
      apt: name={{ item }} state=present update_cache=yes
      sudo: yes
      with_items: 
        - openjdk-7-jre-headless
        - libxt6 
        - libxtst6 
        - libxmu6
        - libxi6
      when: "ansible_os_family == 'Debian'"
    - name: Attach Volume
      include: openstack/tasks/cinder.yml vm_id={{ vm_id }} volume_id={{ volume_id }} volume_device={{ volume_device }} state=attached
      register: volume_attached
      when: not download_iso
    - name: Create mount points
      action: file path={{ iso_mount_point }} state=directory owner={{ ansible_ssh_user }}
      action: file path={{ volume_mount_point }} state=directory owner={{ ansible_ssh_user }}
      sudo: yes
    - name: Check whether ISO image present
      stat: path="{{ volume_mount_point }}/iso"
      register: downloaded_archive
    - name: Download Matlab ISO image
      get_url: url={{ http_repo }} dest={{ volume_mount_point }}/iso
      register: archive
      when: download_iso and downloaded_archive.stat.exists == false
    - name: Mount Matlab Volume
      sudo: yes
      mount: name={{ volume_mount_point }} state=mounted src={{ volume_device }} fstype=auto
      register: volume_mounted
      when: not download_iso
    - name: Mount ISO image
      sudo: yes
      mount: fstype=iso9660 name={{ iso_mount_point }} state=mounted opts=loop src={{ volume_mount_point }}/iso/{{ matlab_version }}_UNIX.iso
      register: iso_mounted
    - name: Prepare Matlab activate file
      command: cp {{ iso_mount_point }}/activate.ini /tmp/activate.ini
    - file: path=/tmp/activate.ini state=touch mode=0644
    - name: customize activate file
      lineinfile: dest=/tmp/activate.ini  regexp=^activateCommand= line=activateCommand=activateOffline
    - name: licenseFile
      lineinfile: dest=/tmp/activate.ini  regexp=^licenseFile= line=licenseFile=/tmp/license.lic
    - name: Prepare installer_input.txt
      command: cp {{ iso_mount_point }}/installer_input.txt /tmp/installer_input.txt
    - file: path=/tmp/installer_input.txt state=touch mode=0644
    - name: customize installer_input.txt
      lineinfile: dest=/tmp/installer_input.txt regexp=^"# fileInstallationKey" line=fileInstallationKey={{ matlab_FIK }}
    - name: Setting silent mode
      lineinfile: dest=/tmp/installer_input.txt regexp=^"# mode" line=mode=silent
    - name: Selecting actibation property file
      lineinfile: dest=/tmp/installer_input.txt regexp=^"# activationPropertiesFile" line="activationPropertiesFile=/tmp/activate.ini"
    - lineinfile: dest=/tmp/installer_input.txt regexp=^"# agreeToLicense" line="agreeToLicense=yes"
    - lineinfile: dest=/tmp/installer_input.txt regexp=^"# licensePath" line="licensePath=/tmp/license.lic"
    # - name: Selecting all toolboxes
      # replace: dest=/tmp/installer_input.txt regexp="^#product(\w+)" replace="product\1"
    # - lineinfile: dest=/tmp/installer_input.txt regexp=^"#product" line="product"
    - name: Create license file
      command: touch /tmp/license.lic
    - name: Set access permission
      file: path=/tmp/license.lic mode=0644
    - name: Configuring license server destination
      lineinfile: dest=/tmp/license.lic line="SERVER {{ matlab_license_server }}"
    - name: Configuring license server destination
      lineinfile: dest=/tmp/license.lic line="USE SERVER"
    - name: Start silent Matlab installation
      command: "{{ iso_mount_point }}/install -inputFile /tmp/installer_input.txt -v "
      sudo: yes
      register: matlab_installed
    - name: Create simlink
      file: src=/usr/local/MATLAB/{{ matlab_version }}/bin/matlab dest=/usr/local/bin/matlab state=link
      sudo: yes
    - name: Cleanup installation files
      file: path={{ item}} state=absent
      with_items:
        - /tmp/installer_input.txt
        - /tmp/activate.ini
        - /tmp/license.lic
    - name: Cleanup Matlab installation logs
      file: path=/tmp/mathworks_root.log state=absent
      when: matlab_installed.stdout.find("End - Successful") != -1
      sudo: yes
    - name: Remove Downloaded ISO image
      file: path={{ volume_mount_point }}/iso/{{ matlab_version }}_UNIX.iso state=absent
      when: download_iso
    - name: Umount Matlab ISO and Matlab Volume
      sudo: yes
      mount: src={{ iso_mount_point }} state=unmounted fstype=auto
      mount: src={{ volume_mount_point }} state=unmounted fstype=auto
    - name: Detach Volume
      include: openstack/tasks/cinder.yml vm_id={{ vm_id }} volume_id={{ volume_id }} volume_device={{ volume_device }} state=detached
      register: volume_attached
      
      
      