---
- name: Ensure /data directory exists
  hosts: usz_data_export:usz_data_import
  tasks:
    - action: file path=/data state=directory owner={{ ansible_ssh_user }}

- name: Ensure scripts and stdout directories exists
  hosts: usz_data_export
  tasks:
    - action: file path=~{{ ansible_ssh_user }}/scripts state=directory owner={{ ansible_ssh_user }}
    - action: file path=~{{ ansible_ssh_user }}/stdout state=directory owner={{ ansible_ssh_user }}

- name: Data export
  hosts: usz_data_export
  vars_files:
    - vars/os
  tasks: 
    - include: common/tasks/nfs.yml
    - action: nfsexport path=/data dest=/etc/exports clients=${groups.usz_data_import} options=rw,no_root_squash,sync
      notify: 
        - ensure nfs service is running
        - reload exports
  handlers:
    - include: common/handlers/main.yml
    - include: slurm/handlers/main.yml
    - include: gridengine/handlers/main.yml

- name: Data Import
  hosts: usz_data_import
  vars_files:
    - vars/os
  tasks: 
    - include: common/tasks/nfs-clients.yml nfsserver=${groups.usz_data_export[0]} nfspath=/data nfsmount=/data remount='true'
    - include: gridengine/tasks/clients.yml
  handlers:
    - include: common/handlers/main.yml
    - include: gridengine/handlers/main.yml
