---
- name: BayeScan download version {{ bayescan_version }}
  get_url: url={{ bayescan_url }} dest={{ download_dir }}
  register: archive
  sudo: yes

- name: BayeScan open archive
  command: unzip {{ download_dir }}/BayeScan{{ bayescan_version }}.zip -d {{ download_dir }}

- name: BayeScan Compile
  command: chdir={{ download_dir }}/BayeScan{{ bayescan_version }}/source make
  register: compiled

- name: BayeScan Create installation folder
  file: path={{ bayescan_install_dir }}/bin state=directory owner={{ ansible_ssh_user }}
  
- name: BayeScan Installing binary
  command: cp {{ download_dir }}/BayeScan{{ bayescan_version }}/source/bayescan_2.1 {{ bayescan_install_dir }}/bin

- name: BayeScan Installing R functions
  command: cp {{ download_dir }}/BayeScan{{ bayescan_version }}/R\ functions/{{ item }} {{ bayescan_install_dir }}/bin
  with_items:
    - AFLP_data_functions.r
    - plot_R.r

- name: BayeScan Cleanup
  file: path={{ download_dir }}/{{ item }} state=absent
  sudo: yes
  with_items:
    - BayeScan{{ bayescan_version }}
    - BayeScan{{ bayescan_version }}.zip
