---
- name: Bowtie download version {{ bowtie_version }}
  get_url: url={{ bowtie_url }} dest={{ download_dir }}
  register: archive

- name: Bowtie open archive
  command: unzip {{ download_dir }}/bowtie2-{{ bowtie_version }}-source.zip -d {{ download_dir }}

- name: Bowtie compile
  command: chdir={{ download_dir }}/bowtie2-{{ bowtie_version }} make
  register: compiled

- name: Bowtie create install folder
  file: path={{ bowtie_install_dir }}/bin state=directory owner={{ ansible_ssh_user }}
  
- name: Bowtie installing binary
  command: cp {{ download_dir }}/bowtie2-{{ bowtie_version }}/{{ item }} {{ bowtie_install_dir }}/bin
  with_items:
    - bowtie2  
    - bowtie2-align-l  
    - bowtie2-align-s  
    - bowtie2-build  
    - bowtie2-build-l  
    - bowtie2-build-s  
    - bowtie2-inspect  
    - bowtie2-inspect-l  
    - bowtie2-inspect-s

- name: Bowtie cleanup
  file: path={{ download_dir }}/{{ item }} state=absent
  sudo: yes
  with_items:
    - bowtie2-{{ bowtie_version }}
    - bowtie2-{{ bowtie_version }}-source.zip

- name: Bowtie adding path to bashrc
  lineinfile: dest=/home/{{ ansible_ssh_user }}/.bashrc state=present line="export PATH={{ bowtie_install_dir }}/bin:$PATH"

