---
- name: Install required dependencies
  apt: name={{ item }} state=present update_cache=yes
  sudo: yes
  with_items: 
    - build-essential
  when: "ansible_os_family == 'Debian'"

- name: Download Bowtie {{ bowtie_version }} from repository
  get_url: url={{ bowtie_url }} dest={{ download_dir }}
  register: archive
  sudo: yes

- name: Open archive
  command: unzip {{ download_dir }}/bowtie2-{{ bowtie_version }}-source.zip -d {{ download_dir }}

- name: Compile Bowtie
  command: chdir={{ download_dir }}/bowtie2-{{ bowtie_version }} make
  register: compiled

- name: Create Bowtie folder
  file: path={{ bowtie_install_dir }}/bin state=directory owner={{ ansible_ssh_user }}
  sudo: yes
  
- name: Installing Bowtie binary
  command: cp {{ download_dir }}/bowtie2-{{ bowtie_version }}/{{ item }} {{ bowtie_install_dir }}/bin
  with_items:
    - bowtie2  
    - bowtie2-align-l  
    - bowtie2-align-s  
    - bowtie2-build  
    - bowtie2-build-l  
    - bowtie2-build-s  
    - bowtie2-inspect  
    - bowtie2-inspect-l  
    - bowtie2-inspect-s

- name: Cleanup
  file: path={{ download_dir }}/{{ item }} state=absent
  sudo: yes
  with_items:
    - bowtie2-{{ bowtie_version }}
    - bowtie2-{{ bowtie_version }}-source.zip
