---
- name: BWA download version {{ bwa_version }}
  get_url: url={{ bwa_url }} dest={{ download_dir }}
  register: archive

- name: BWA open archive
  command: tar xfj {{ download_dir }}/bwa-{{ bwa_version }}.tar.bz2 -C {{ download_dir }}

- name: BWA compile 
  command: chdir={{ download_dir }}/bwa-{{ bwa_version }} make
  register: compiled

- name: BWA create folder
  file: path={{ bwa_install_dir }}/bin state=directory owner={{ ansible_ssh_user }}
  
- name: BWA installing binary
  command: cp {{ download_dir }}/bwa-{{ bwa_version }}/bwa {{ bwa_install_dir }}/bin

- name: BWA cleanup
  file: path={{ download_dir }}/{{ item }} state=absent
  sudo: yes
  with_items:
    - bwa-{{ bwa_version }}
    - bwa-{{ bwa_version }}.tar.bz2
