---
- name: Install required dependencies
  apt: name={{ item }} state=present update_cache=yes
  sudo: yes
  with_items: 
    - build-essential
  when: "ansible_os_family == 'Debian'"

- name: Download BWA {{ bwa_version }} from repository
  get_url: url={{ bwa_url }} dest={{ download_dir }}
  register: archive
  sudo: yes

- name: Open archive
  command: tar xfj {{ download_dir }}/bwa-{{ bwa_version }}.tar.bz2 -C {{ download_dir }}

- name: Compile BWA
  command: chdir={{ download_dir }}/bwa-{{ bwa_version }} make
  register: compiled

- name: Create Bwa folder
  file: path={{ bwa_install_dir }}/bin state=directory owner={{ ansible_ssh_user }}
  sudo: yes
  
- name: Installing BWA binary
  command: cp {{ download_dir }}/bwa-{{ bwa_version }}/bwa {{ bwa_install_dir }}/bin

- name: Cleanup
  file: path={{ download_dir }}/{{ item }} state=absent
  sudo: yes
  with_items:
    - bwa-{{ bwa_version }}
    - bwa-{{ bwa_version }}.tar.bz2
