---
- name: Epacts prepare destination folder in {{ epacts_install_dir }} 
  command: mkdir -p {{ epacts_install_dir }}

- name: Epacts Check whether archive has been previosuly downloaded
  stat: path="{{ download_dir }}/EPACTS-{{ epacts_version }}.tar.gz"
  register: downloaded_archive 

- name: Epacts Download archive
  get_url: url={{ epacts_url }} dest={{ download_dir }}
  when: downloaded_archive.stat.exists == false
  register: archive

- name: Epacts open archive
  command: tar xfz {{ download_dir }}/EPACTS-{{ epacts_version }}.tar.gz -C {{ download_dir }}
  register: archive_open

- name: Epacts compile and install
  command: chdir={{ download_dir }}/EPACTS-{{ epacts_version }} {{ item }}
  with_items:
    - ./configure --prefix={{ epacts_install_dir }}
    - make
    - make install

- name: Epacts cleanup
  file: path={{ download_dir }}/{{ item }} state=absent
  sudo: yes
  with_items:
    - EPACTS-{{ epacts_version }}
    - EPACTS-{{ epacts_version }}.tar.gz

