---
- name: Stacks download version {{ stacks_version }}
  get_url: url={{ stacks_url }} dest={{ download_dir }}
  register: archive

- name: Stacks open archive
  command: tar xfz {{ download_dir }}/stacks-{{ stacks_version }}.tar.gz -C {{ download_dir }}

- name: Stacks compile
  command: chdir={{ download_dir }}/stacks-{{ stacks_version }} {{ item }}
  register: compiled
  with_items:
    - ./configure --prefix={{ stacks_install_dir }}
    - make
    - make install

- name: Stacks cleanup
  file: path={{ download_dir }}/{{ item }} state=absent
  sudo: yes
  with_items:
    - stacks-{{ stacks_version }}.tar.gz
    - stacks-{{ stacks_version }}