---
- name: Structure download version {{ structure_version }}
  get_url: url={{ structure_url }} dest={{ download_dir }}
  register: archive

- name: Structure open archive
  command: tar xfz {{ download_dir }}/structure_kernel_source.tar.gz -C {{ download_dir }}

- name: Structure compile
  command: chdir={{ download_dir }}/structure_kernel_src {{ item }}
  register: compiled
  with_items:
    - make

- name: Structure create install dir
  file: path={{ structure_install_dir }}/bin state=directory owner={{ ansible_ssh_user }}

- name: Structure Copy binary in install dir
  command: cp {{ download_dir }}/structure_kernel_src/structure {{ structure_install_dir }}/bin

- name: Structure cleanup
  file: path={{ download_dir }}/{{ item }} state=absent
  sudo: yes
  with_items:
    - structure_kernel_source.tar.gz
    - structure_kernel_src